apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ospl-main-daemon.fullname" . }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "ospl-main-daemon.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ospl-main-daemon.selectorLabels" . | nindent 6 }}
  replicas: 0
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ospl-main-daemon.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LSST_DOMAIN_ID
              value: {{ .Values.domainId | quote }}
          {{- if ne ( .Values.domainId | toString ) "0" }}
            - name: LSST_DOMAIN_NAME
              value: "ospl_sp_ddsi_{{ .Values.domainId }}"
          {{- end }}
          {{- if or .Values.env }}
          {{- range $env_var, $env_value := .Values.env }}
            - name: {{ $env_var }}
              value: {{ $env_value | quote }}
          {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.initContainer }}
      initContainers:
        - name: {{ include "ospl-main-daemon.fullname" . }}-route-fixer
          image: "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag }}"
          imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
          securityContext:
            privileged: true
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
