apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  completions: 1
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LSST_DDS_DOMAIN
              value: "{{ .Values.env.lsstDdsDomain }}"
            - name: CSC_INDEX
              value: "{{ .Values.env.cscIndex }}"
            - name: CSC_MODE
              value: "{{ .Values.env.cscMode }}"
      restartPolicy: Never
  ttlSecondsAfterFinished: 5
