apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  {{- include "multicast.annotation" . | nindent 2 }}
spec:
  replicas: 1
  template:
    metadata:
      {{- include "multicast.annotation" . | nindent 4 }}
    spec:
      {{- include "multicast.annotation" . | nindent 6 }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          stdin: true
          tty: true
          {{- if .Values.env }}
          env:
          {{- range $env_var, $env_value := .Values.env }}
            - name: {{ $env_var }}
              value: {{ $env_value | quote }}
          {{- end }}
          {{- end }}
{{- if .Values.entrypoint }}
          volumeMounts:
            - name: entrypoint
              mountPath: /home/saluser/.setup.sh
              subPath: .setup.sh
      volumes:
        - name: entrypoint
          configMap:
            name: {{ .Release.Name }}-entrypoint
            items:
              - key: .setup.sh
                path: .setup.sh
{{- end }}
      restartPolicy: Never
