apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    csc: {{ .Release.Name }}
  {{- if and $.Values.useMulticast (ne ( $.Values.useMulticast | toString ) "<nil>" ) }}
  {{- include "multicast.annotation" . | nindent 2 }}
  {{- end }}
spec:
  completions: 1
  template:
    metadata:
      labels:
        csc: {{ .Release.Name }}
      {{- if and $.Values.useMulticast (ne ( $.Values.useMulticast | toString ) "<nil>" ) }}
      {{- include "multicast.annotation" . | nindent 6 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          stdin: true
          tty: true
          {{- if .Values.env }}
          env:
          {{- range $env_var, $env_value := .Values.env }}
            - name: {{ $env_var }}
              value: {{ $env_value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: osplconfig
              mountPath: /opt/OpenSpliceDDS/{{ $.Values.osplVersion }}/HDE/x86_64.linux/etc/config/ospl.xml
              subPath: ospl.xml
            - name: osplshmem
              mountPath: /tmp
          {{- if .Values.entrypoint }}
            - name: entrypoint
              mountPath: /home/saluser/.startup.sh
              subPath: .startup.sh
          {{- end }}
          {{- if .Values.pvcMountpoint }}
          {{- range $values := .Values.pvcMountpoint }}
            - name: {{ $values.name }}
              mountPath: {{ $values.path }}
          {{- end}}
          {{- end}}
          {{- if .Values.nfsMountpoint }}
          {{- range $values := .Values.nfsMountpoint }}
            - name: {{ $values.name }}
              mountPath: {{ $values.containerPath }}
              readOnly: {{ $values.readOnly }}
          {{- end}}
          {{- end}}
      {{- if .Values.initContainer }}
      initContainers:
        - name: {{ .Release.Name }}-route-fixer
          image: "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag }}"
          imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
          securityContext:
            privileged: true
      {{- end }} 
      volumes:
        - name: osplconfig
          configMap:
            name: {{ $.Values.namespace }}-ospl-config
            items:
              - key: ospl.xml
                path: ospl.xml
        - name: osplshmem
          hostPath:
            path: {{ $.Values.shmemDir | default "/tmp/openshmem" }}
      {{- if .Values.entrypoint }}
        - name: entrypoint
          configMap:
            name: {{ .Release.Name }}-entrypoint
            items:
              - key: .startup.sh
                path: .startup.sh
      {{- end }}
      {{- if .Values.pvcMountpoint }}
      {{- range $values := .Values.pvcMountpoint }}
        - name: {{ $values.name }}
          persistentVolumeClaim:
            claimName: {{ $.Release.Name }}-{{ $values.name }}-pvc
      {{- end }}
      {{- end }}
      {{- if .Values.nfsMountpoint }}
      {{- range $values := .Values.nfsMountpoint }}
        - name: {{ $values.name }}
          nfs:
            path: {{ $values.serverPath }}
            readOnly: {{ $values.readOnly }}
            server: {{ $values.server }}
      {{- end }}
      {{- end }}
      restartPolicy: Never
      {{- if .Values.image.nexus3 }}
      imagePullSecrets:
        - name: {{ $.Values.namespace }}-{{ $.Values.image.nexus3 }}
      {{- end }}
      hostIPC: {{ or $.Values.useHostIpc (eq ( $.Values.useHostIpc | toString ) "<nil>" ) }}
      hostPID: {{ or $.Values.useHostPid (eq ( $.Values.useHostPid | toString ) "<nil>" ) }}
