{{- if hasKey .Values.image "useNexus3" }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: nexus3-docker
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if eq $.Values.deployEnv "base" }}
  path: secret/k8s_operator/base-lsp.lsst.codes/ts/software/nexus3-docker
  {{- else if eq $.Values.deployEnv "summit" }}
  path: secret/k8s_operator/summit-lsp.lsst.codes/ts/software/nexus3-docker
  {{- else if eq $.Values.deployEnv "ncsa-teststand" }}
  path: secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu/ts/software/nexus3-docker
  {{- else if eq $.Values.deployEnv "ncsa-lsp-int" }}
  path: secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/ts/software/nexus3-docker
  {{- else }}
  path: secret/dm/square/efd/{{ $.Values.deployEnv }}/nexus3-docker
  {{- end }}
  type: kubernetes.io/dockerconfigjson
{{- end }}
