# -- This section holds the configuration of the container image
image:
  # -- The Docker registry name of the container image
  repository: ts-dockerhub.lsst.org/ospl-daemon
  # -- The tag of the container image
  tag: c0010
  # -- The policy to apply when pulling an image for deployment
  pullPolicy: IfNotPresent
# -- Specify the domainId for the daemon
domainId: 0
# -- This key allows specification of a script to override the entrypoint.
# -- The list of pull secrets needed for the images.
# If this section is used, each object listed can have the following attributes defined:
# _name_ (The label identifying the pull-secret to use)
imagePullSecrets: []
# -- This is the namespace in which the OSPL daemon will be placed
namespace: ospl-daemon
# -- This section holds a set of key, value pairs for environmental variables
env: {}
# -- Adds an extra string to the release name.
nameOverride: ""
# -- Specify the deployed application name specifically. Overrides all other names.
fullnameOverride: ""
# -- This allows the specification of pod annotations.
annotations:
  k8s.v1.cni.cncf.io/networks: kube-system/macvlan-conf
# -- This section sets the optional use of an init container for multus networking.
# If this section is used, the following attributes must to be specified:
# _repository_ (The Docker registry name of the init container image),
# _tag_ (The tag of the init container image),
# _pullPolicy_ (The policy to apply when pulling an image for init container deployment)
initContainer: {}
# -- This allows the specification of resources (CPU, memory) requires to run the container
resources: {}
# -- This allows the specification of using specific nodes to run the pod
nodeSelector: {}
# -- This specifies the tolerations of the pod for any system taints
tolerations: []
# -- This specifies the scheduling constraints of the pod
affinity: {}
