image:
  # -- The Docker registry name for the container image.
  repository: ts-dockerhub.lsst.org/rubintv-broadcaster
  # -- The tag of the container image to use.
  tag: develop
  # -- The policy to apply when pulling an image for deployment.
  pullPolicy: IfNotPresent
# -- This is the namespace where the applications will be deployed.
namespace: rubintv-broadcaster
# -- List of the script to run for the broadcaster.
scripts: []
# -- This section holds a set of key, value pairs for environmental variables (ENV_VAR: value).
# NOTE: RUN_ARG is taken care of by the chart using _script_.
env: {}
# -- The Vault prefix path
vaultPrefixPath: ""
# The key for the pull secrets including any sub-paths.
pullSecretsPath: ""
# -- This key allows specification of a script to override the entrypoint.
# -- The list of pull secrets needed for the images.
# If this section is used, each object listed can have the following attributes defined:
# _name_ (The label identifying the pull-secret to use)
imagePullSecrets: []
# -- This section holds the information necessary to create a NFS mount for the container.
# If this section is used, each object listed can have the following attributes defined:
# _name_ (A label identifier for the mountpoint),
# _containerPath_ (The path inside the container to mount),
# _readOnly_ (This sets if the NFS mount is read only or read/write),
# _server_ (The hostname of the NFS server),
# _serverPath_ (The path exported by the NFS server)
nfsMountpoint: []
# -- The key for the credentials including any sub-paths.
credentialSecretsPath: ""
# -- The name of the expected credential file for the broadcasters
credentialFile: ""
# -- Adds an extra string to the release name.
nameOverride: ""
# -- Specify the deployed application name specifically. Overrides all other names.
fullnameOverride: ""
# -- This allows the specification of pod annotations.
podAnnotations: {}
# -- This allows the specification of resources (CPU, memory) requires to run the container.
resources: {}
# -- This allows the specification of using specific nodes to run the pod.
nodeSelector: {}
# -- This specifies the tolerations of the pod for any system taints.
tolerations: []
# -- This specifies the scheduling constraints of the pod.
affinity: {}
