image:
  repository: lsstts/dsm
  tag: develop
  pullPolicy: IfNotPresent

env:
  LSST_DDS_PARTITION_PREFIX: citest
  CSC_INDEX: 1
  CSC_MODE: 1

osplVersion: V6.9.0
namespace: csc

nfsMountpoint:
  - name: path1
    containerPath: /home/saluser/telemetry
    readOnly: true
    server: server1.mydomain.org
    serverPath: /nfs/user1
  - name: path2
    containerPath: /tmp
    readOnly: true
    server: server2.mydomain.org
    serverPath: /nfs/tmp
  - name: path3
    containerPath: /mnt
    readOnly: true
    server: server3.mydomain.org
    serverPath: /nfs/extrastuff
