# Default values for kafka-producers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: lsstts/dsm
  tag: develop
  pullPolicy: IfNotPresent

env:
  lsst_dds_domain: rubinobs
  csc_index: 1
  csc_mode: 2
