# Default values for kafka-producers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: lsstts/dsm
  tag: develop
  pullPolicy: IfNotPresent

env:
  lsstDdsDomain: rubinobs
  cscIndex: 1
  cscMode: 2
