namespace: love

image:
  repository: nginx
  tag: 1.14.2
  pullPolicy: IfNotPresent
serviceType: ClusterIP
ports:
  container: 80
  node: 30000
ingress:
  hostname: love.local
  httpPath: /
config: |
  server {
    listen 80;
    server_name localhost;
    location / {
      root   /usr/src/love-frontend;
      try_files $uri$args $uri$args/ $uri/ /index.html;
    }
    location /manager {
        proxy_pass http://love-manager-service:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_redirect off;
    }
    location /manager/static {
        alias /usr/src/love-manager/static;
    }
    location /manager/media {
        alias /usr/src/love-manager/media;
    }
  }
initContainers:
  frontend:
    image: 
      repository: lsstts/love-frontend
      tag: develop
  manager:
    image: 
      repository: lsstts/love-manager
      tag: develop
staticStore:
  name: love-nginx-static
  storageClass: local-store
  accessMode: ReadWriteMany
  claimSize: 2Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
