producers:
  auxtel:
    image:
      tag: v1.1.0_salobj_v5.7.0_xml_4.8.0
      pullPolicy: Always
    env:
      partitions: 3
      waitAck: all
      replication: 10
      logLevel: 50
    cscs: >-
      ATPtg
      ATDome
  eas:
    env:
      extras:
        TOPIC_CONFIG_FILE: /tmp/test.yaml
    cscs: >-
      Test
      DIMM

image:
  nexus3: nexus3-docker

shmemDir: /my/test
