apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rubintv-broadcaster.fullname" $ }}-env-configmap
  namespace: {{ .Values.namespace }}
data:
  GOOGLE_APPLICATION_CREDENTIALS: "/etc/{{ include "rubintv-broadcaster.fullname" $ }}/creds/{{ .Values.credentialFile }}"
