---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "rubintv-broadcaster.fullname" . }}-pull-secret
  labels:
    app.kubernetes.io/name: {{ include "rubintv-broadcaster.name" . }}
spec:
  path: {{ required "vaultPrefixPath must be set" .Values.vaultPrefixPath }}/{{ required "pullSecretsPath must be set" .Values.pullSecretsPath }}
  type: kubernetes.io/dockerconfigjson
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "rubintv-broadcaster.fullname" . }}-google-creds
  labels:
    app.kubernetes.io/name: {{ include "rubintv-broadcaster.name" . }}
spec:
  path: {{ required "vaultPrefixPath must be set" .Values.vaultPrefixPath }}/{{ required "credentialSecretsPath must be set" .Values.credentialSecretsPath }}
  type: Opaque
