apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "love-nginx.fullname" . }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "love-nginx.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "love-nginx.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicas | default 1 }}
  template:
    metadata:
      labels:
        {{- include "love-nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "love-nginx.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.container }}
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            readOnly: true
            name: nginx-conf
        {{- if .Values.pvcMountpoint }}
        {{- range $values := .Values.pvcMountpoint }}
          - mountPath: {{ $values.path }}
            name: {{ $values.name }}
        {{- end }}
        {{- end }}
        {{- with $.Values.resources }}
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
        {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      {{- if .Values.pvcMountpoint }}
      {{- range $values := .Values.pvcMountpoint }}
        - name: {{ $values.name }}
          persistentVolumeClaim:
            claimName: {{ $values.name }}-pvc
      {{- end }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
