apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "love-nginx.fullname" . }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "love-nginx.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "love-nginx.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicas | default 1 }}
  template:
    metadata:
      labels:
        {{- include "love-nginx.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: love-frontend
        image: "{{ .Values.initContainers.frontend.image.repository }}:{{ .Values.initContainers.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "/bin/sh", "-c", "cp -Rv /usr/src/love/ /usr/src/love-frontend" ]
        volumeMounts:
          - mountPath: /usr/src
            name: {{ .Values.staticStore.name }}
      - name: love-manager-static
        image: "{{ .Values.initContainers.manager.image.repository }}:{{ .Values.initContainers.manager.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "/bin/sh", "-c", "mkdir -p /usr/src/love-manager/media/thumbnails; mkdir -p /usr/src/love-manager/media/configs; cp -Rv /usr/src/love/manager/static /usr/src/love-manager; cp -uv /usr/src/love/manager/ui_framework/fixtures/thumbnails/* /usr/src/love-manager/media/thumbnails; cp -uv /usr/src/love/manager/api/fixtures/configs/* /usr/src/love-manager/media/configs" ]
        volumeMounts:
          - mountPath: /usr/src
            name: {{ .Values.staticStore.name }}
      containers:
      - name: {{ include "love-nginx.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.container }}
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            readOnly: true
            name: nginx-conf
          - mountPath: /usr/src
            name: {{ .Values.staticStore.name }}
        {{- with $.Values.resources }}
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
        {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: {{ .Values.staticStore.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.staticStore.name }}-pvc
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
