---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "love-nginx.fullname" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/instance: {{ include "love-nginx.fullname" . }}
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.ports.container }}
      targetPort: {{ .Values.ports.container }}
      {{- if ne .Values.serviceType "ClusterIP" }}
      nodePort: {{ .Values.ports.node }}
      {{- end }}
