{{- if .Values.pvcMountpoint }}
{{- range $values := .Values.pvcMountpoint }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $values.name }}-pvc
spec:
  accessModes:
    - {{ $values.accessMode | quote }}
  resources:
    requests:
      storage: {{ $values.claimSize }}
  storageClassName: {{ $values.storageClass }}
{{- end }}
{{- end }}
