image:
  repository: lsstts/dsm
  tag: develop
  pullPolicy: IfNotPresent

env:
  LSST_DDS_PARTITION_PREFIX: citest
  CSC_INDEX: 1
  CSC_MODE: 1

osplVersion: V6.9.0
namespace: csc

envSecrets:
  - name: SECRET_NEEDED_1
    secretName: top-key
    secretKey: i-have-one-secret
  - name: SECRET_NEEDED_2
    secretName: top-key
    secretKey: i-have-another-secret
