image:
  repository: lsstts/dsm
  tag: develop
  pullPolicy: IfNotPresent

env:
  LSST_DDS_PARTITION_PREFIX: citest
  CSC_INDEX: 1
  CSC_MODE: 1

osplVersion: V6.9.0
namespace: csc

envSecrets:
  - key: SECRET_NEEDED_1
    value: i-have-one-secret
  - key: SECRET_NEEDED_2
    value: i-have-another-secret
