image:
  repository: lsstts/dsm
  tag: develop
  pullPolicy: IfNotPresent

env:
  LSST_DDS_PARTITION_PREFIX: citest
  CSC_INDEX: 1
  CSC_MODE: 1

osplVersion: V6.9.0
namespace: csc

pvcMountpoint:
  - name: path1
    path: /home/saluser/telemetry
    accessMode: ReadWriteOnce
    ids:
      uid: 123
    claimSize: 1G
    storageClass: local
  - name: path2
    path: /tmp
    ids:
      gid: 432
    accessMode: ReadOnlyMany
    claimSize: 500Mb
    storageClass: local
  - name: path3
    path: /mnt
    ids:
      uid: 123
      gid: 432
    accessMode: ReadWriteMany
    claimSize: 500G
    storageClass: rook-ceph-block
