image:
  repository: lsstts/dsm
  tag: develop
  pullPolicy: IfNotPresent

env:
  LSST_DDS_PARTITION_PREFIX: citest
  CSC_INDEX: 1
  CSC_MODE: 1

osplVersion: V6.9.0
namespace: csc

annotations:
  k8s.v1.cni.cncf.io/networks: kube-system/macvlan-conf
initContainer:
  repository: lsstit/ddsnet4u
  tag: latest
  pullPolicy: IfNotPresent 
