namespace: love
secret_path: lsst.local
image:
  repository: lsstts/love-manager
  tag: develop
  pullPolicy: IfNotPresent
serviceType: ClusterIP
ports:
  container: 8000
  node: 30000
ingress:
  hostname: love.local
  httpPath: /
pvcMountpoint:
- name: love-manager
  path: /usr/src/love/manager
envSecretKeyName: love
env:
  - var: SECRET_KEY
    value: manager-secret-key
    isSecret: true
  - var: PROCESS_CONNECTION_PASS
    value: manager-process-connection-password
    isSecret: true
  - var: ADMIN_USER_PASS
    value: manager-admin-password
    isSecret: true
  - var: USER_USER_PASS
    value: manager-user-user-password
    isSecret: true
  - var: CMD_USER_PASS
    value: manager-cmd-user-password
    isSecret: true
  - var: SERVER_URL
    value: love.lsst.local
  - var: LOVE_PRODUCER_WEBSOCKET_HOST
    value: love-service/manager/ws/subscription
  - var: COMMANDER_HOSTNAME
    value: love-commander-service
  - var: COMMANDER_PORT
    value: 5000
config: |
    {
      "alarms": {
        "minSeveritySound": "serious",
        "minSeverityNotification": "warning"
      },
      "camFeeds": {
        "generic": "/gencam",
        "allSky": "/gencam"
      }
    }
database:
  image:
    repository: postgres
    tag: 12.0
    pullPolicy: IfNotPresent
  port: 5432
  pvcMountpoint:
    name: love-manager-database
    path: /var/lib/postgresql/data
    storageClass: local-store
    accessMode: ReadWriteMany
    claimSize: 2Gi
  env:
    - var: DB_ENGINE
      value: postgresql
    - var: DB_NAME
      value: postgres
    - var: DB_USER
      value: postgres
    - var: DB_HOST
      value: love-manager-database-service
    - var: DB_PORT
      value: 5432
    - var: DB_PASS
      value: database-password
      isSecret: true
redis:
  image:
    repository: redis
    tag: 5.0.3
    pullPolicy: IfNotPresent
  env:
    - var: REDIS_HOST
      value: love-manager-redis-service
    - var: REDIS_PASS
      value: redis-password
      isSecret: true
  port: 6379

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
