namespace: love
secret_path: lsst.local
image:
  repository: lsstts/love-manager
  tag: develop
  pullPolicy: IfNotPresent
serviceType: ClusterIP
ports:
  container: 8000
  node: 30000
envSecretKeyName: love
env:
  SERVER_URL: love.lsst.local
  LOVE_PRODUCER_WEBSOCKET_HOST: love-service/manager/ws/subscription
  COMMANDER_HOSTNAME: love-commander-service
  COMMANDER_PORT: 5000
  DB_ENGINE: postgresql
  DB_NAME: postgres
  DB_USER: postgres
  DB_HOST: love-manager-database-service
  DB_PORT: 5432
  REDIS_HOST: love-manager-redis-service
envSecrets:
  SECRET_KEY: manager-secret-key
  PROCESS_CONNECTION_PASS: manager-process-connection-password
  ADMIN_USER_PASS: manager-admin-user-password
  USER_USER_PASS: manager-user-user-password
  CMD_USER_PASS: manager-cmd-user-password
  DB_PASS: database-password
  REDIS_PASS: redis-password
configMount: /usr/src/love/manager/config
config: |
    {
      "alarms": {
        "minSeveritySound": "serious",
        "minSeverityNotification": "warning"
      },
      "camFeeds": {
        "generic": "/gencam",
        "allSky": "/gencam"
      }
    }
database:
  image:
    repository: postgres
    tag: "12.0"
    pullPolicy: IfNotPresent
  port: 5432
  pvcMountpoint:
    name: love-manager-database
    path: /var/lib/postgresql/data
    storageClass: local-store
    accessMode: ReadWriteMany
    claimSize: 2Gi
  env:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
  envSecrets:
    POSTGRES_PASSWORD: database-password
redis:
  image:
    repository: redis
    tag: 5.0.3
    pullPolicy: IfNotPresent
  envSecrets:
    REDIS_PASS: redis-password
  port: 6379

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
