apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "love-manager.database.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "love-manager.database.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "love-manager.database.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.database.replicas | default 1 }}
  template:
    metadata:
      labels:
        {{- include "love-manager.database.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "love-manager.database.fullname" . }}
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.database.port }}
        volumeMounts:
          - mountPath: {{ .Values.database.pvcMountpoint.path }}
            name: {{ .Values.database.pvcMountpoint.name }}-pvc
        env:
        {{- $data := dict "env" .Values.database.env "secretName" .Values.envSecretKeyName }}
        {{- include "helpers.envFromList" $data | indent 10 }}
        {{- with $.Values.resources }}
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
        {{- end }}
      volumes:
        - name: {{ .Values.database.pvcMountpoint.name }}-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.database.pvcMountpoint.name }}-pvc
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
