apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pvcMountpoint.name }}-pvc
spec:
  accessModes:
    - {{ .Values.database.pvcMountpoint.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.database.pvcMountpoint.claimSize }}
