{{- range $item := concat .Values.redis.env .Values.database.env .Values.env }}
{{- if $item.isSecret }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $item.value }}
  namespace: {{ $.Values.namespace }}
spec:
  path: secret/k8s_operator/{{ $.Values.secret_path }}/ts/software/{{ $item.value }}
  type: Opaque
{{- end }}
{{- end }}
