---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $.Values.envSecretKeyName }}-secrets
  namespace: {{ $.Values.namespace }}
spec:
  path: secret/k8s_operator/{{ $.Values.secret_path }}/ts/software/{{ $.Values.envSecretKeyName }}
  type: Opaque
