apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "love-frontend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "love-frontend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "love-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "love-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "love-frontend.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "/bin/sh", "-c", "cp -R /usr/src/love/ /usr/src/love-frontend" ]
        volumeMounts:
        {{- if .Values.pvcMountpoint }}
        {{- range $values := .Values.pvcMountpoint }}
          - mountPath: {{ $values.path }}
            name: {{ $values.name }}
        {{- end }}
        {{- end }}
        {{- with $.Values.resources }}
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
        {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
      {{- if .Values.pvcMountpoint }}
      {{- range $values := .Values.pvcMountpoint }}
        - name: {{ $values.name }}
          persistentVolumeClaim:
            claimName: {{ $values.name }}-pvc
      {{- end }}
      {{- end }}
      {{- if $.Values.image.nexus3 }}
      imagePullSecrets:
        - name: {{ $.Values.namespace }}-{{ $.Values.image.nexus3 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
