apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  {{- include "multicast.annotation" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
      {{- include "multicast.annotation" . | nindent 6  }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          stdin: true
          tty: true
          {{- if .Values.env }}
          env:
          {{- range $env_var, $env_value := .Values.env }}
            - name: {{ $env_var }}
              value: {{ $env_value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: osplconfig
              mountPath: /opt/OpenSpliceDDS/{{ .Values.osplVersion }}/HDE/x86_64.linux/etc/config/ospl.xml
              subPath: ospl.xml
            - name: osplshmem
              mountPath: /tmp
      {{- if .Values.initContainer }}
      initContainers:
        - name: {{ .Release.Name }}-route-fixer
          image: "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag }}"
          imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
          securityContext:
            privledged: true
      {{- end }} 
      volumes:
        - name: osplconfig
          configMap:
            name: {{ .Values.namespace }}-ospl-config
            items:
              - key: ospl.xml
                path: ospl.xml
        - name: osplshmem
          hostPath:
            path: {{ .Values.shmemDir }}
            type: DirectoryOrCreate
      {{- if .Values.image.nexus3 }}
      imagePullSecrets:
        - name: {{ .Values.namespace }}-{{ .Values.image.nexus3 }}
      {{- end }}
      hostIPC: {{ or $.Values.useHostIpc (eq ( $.Values.useHostIpc | toString ) "<nil>" ) }}
      hostPID: {{ or $.Values.useHostPid (eq ( $.Values.useHostPid | toString ) "<nil>" ) }}
