image:
  repository: ts-dockerhub.lsst.org/ospl-daemon 
  tag: c0010
  pullPolicy: IfNotPresent
  nexus3: nexus3-docker

env:
  LSST_DDS_PARTITION_PREFIX: ncsa

osplVersion: V6.10.4
shmemDir: /tmp/test
namespace: ospl-daemon
